name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "oh wow, you did your first issue! i'm so proud of you. JUICE   -Kart"
        pr-message: "you pulling my leg? first pull request?????? such a JUICY moment. JUICE   -Kart"
